// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6htJpMeQXuT2x_w6Gjvxy8zFHsqtnd8',
    appId: '1:1067426349572:web:f0e9ccb552421743bcab51',
    messagingSenderId: '1067426349572',
    projectId: 'mossyoga-101',
    authDomain: 'mossyoga-101.firebaseapp.com',
    storageBucket: 'mossyoga-101.appspot.com',
    measurementId: 'G-6BREDRNB91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5dN2-hMlL40jRXU3Arq8QAxyEbggN_cE',
    appId: '1:1067426349572:android:91ac00c5e7639cf5bcab51',
    messagingSenderId: '1067426349572',
    projectId: 'mossyoga-101',
    storageBucket: 'mossyoga-101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgLGUepKPwEObCIcQZVNuSyOho88rITIY',
    appId: '1:1067426349572:ios:a9c61823a278c0f8bcab51',
    messagingSenderId: '1067426349572',
    projectId: 'mossyoga-101',
    storageBucket: 'mossyoga-101.appspot.com',
    iosClientId: '1067426349572-sqln0hp1l6l6eeltqnajf2jrq45lu1lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mossYoga',
  );
}
